with WORD_PARAMETERS; use WORD_PARAMETERS;
with Text_IO;

package Words_Help is

   procedure SHOW_HELP (Line : in String; Output : Text_IO.File_Type);

private

   type Main_Help_Type is array (Positive range <>) of String (1 .. 79);

   procedure Put (HELP : in Main_Help_Type; Output : in Text_IO.File_Type);

   Bold_Next      : constant String (1 .. 79) := (others => 'B');
   Skip_Next      : constant String (1 .. 79) := (others => 'S');
   Underline_Next : constant String (1 .. 79) := (others => 'U');

   GENERAL_HELP : constant Main_Help_Type :=
     (Underline_Next,
      "HOW TO READ AN INFLECTION LINE|                                                ",
      Skip_Next, Bold_Next,
      "Example:|                                                                      ",
      Bold_Next,
      "am.o             V          1 1 PRES ACTIVE  IND 1 S  Always  mostfreq|        ",
      Bold_Next,
      "[root].[inflect] [pt.spch.] [grammar]                 [age]   [infl. freq.]|   ",
      "     TYPE ? GRAMMAR to learn more about the [grammar] columns|                 ",
      "     TYPE ? AGE to learn more about the [age] column|                          ",
      "     TYPE ? FREQ to learn more about the [infl. freq.] column|                 ",
      Skip_Next, Underline_Next,
      "HOW TO READ A DICTIONARY LINE|                                                 ",
      Skip_Next, Bold_Next,
      "Example:|                                                                      ",
      Bold_Next,
      "amo, amare, amavi, amatus   V          (1st)       [XXXAO]      veryfreq|      ",
      Bold_Next,
      "[standard dictionary forms] [pt.spch.] [decl/conj] [dict. code] [word freq.]|  ",
      "     TYPE ? CODES to learn more about the [dict. codes] columns|               ",
      "     TYPE ? FREQ to learn more about the [freq.] column|                       ",
      Skip_Next, Underline_Next,
      "HOW TO READ ABBREVIATIONS IN A MEANING (DEFINITION) LINE|                      ",
      Skip_Next,
      "TYPE ? MEANING for the abbreviations used in word meaning (definition) lines.| ",
      Skip_Next, Underline_Next,
      "OTHER FEATURES|                                                                ",
      Skip_Next,
      "TYPE ? ARG to learn about command-line arguments and operation modes|          ",
      "TYPE " & CHANGE_LANGUAGE_CHARACTER & "E for English=>Latin mode or " &
      CHANGE_LANGUAGE_CHARACTER &
      "L for Latin => English mode.|              ",
      "TYPE # to set 'user' parameters.  TYPE ! to set advanced ('developer') options.");

   GRAMMAR_HELP : constant Main_Help_Type :=
     (Underline_Next,
      "GRAMMAR COLUMNS IN INFLECTION RESULTS|                                         ",
      Skip_Next, Bold_Next,
      "FEATURES COMMON AMONG MOST ENTRY TYPES:|                                       ",
      "In most contexts you should read an 'X' as 'all/none/unknown'.|                ",
      "     You should not infer anything from an 'X'.|                               ",
      Skip_Next,
      "The PART OF SPEECH code immediately follows inflected form.|                   ",
      "The codes are self-descriptive. E.g., N, V, ADJ, NUM, ADV, VPAR, SUPINE|       ",
      Skip_Next,
      "Next come two numbers, the CASE or CONJUGATION number is first, followed|      ",
      "     by a 'VARIANT' number. The VARIANT specifies the ending patterns, which|  ",
      "     are defined in INFLECTS.LAT. MOST VARIANTS ARE NOT MEANINGFUL CATEGORIES| ",
      "     but inventions for the program logic. They may be useful references:|     ",
      "     if a variant is higher than about 3, the word may be highly irregular or| ",
      "     permit unusual inflections.  Refer to INFLECTS.LAT for the possibilities.|",
      Skip_Next,
      "The last two columns are the age and inflection FREQUENCY. The abbreviations|  ",
      "    are self-descriptive, but there are a few nuances.|                        ",
      "    TYPE ? AGE to learn more about the age codes.|                             ",
      "    TYPE ? FREQ to learn more about the frequency codes.|                      ",
      Skip_Next, Bold_Next,
      "VERB RESULTS. E.g.,|                                                           ",
      Bold_Next,
      "am.o                 V      1 1 PRES ACTIVE  IND 1 S      Always    mostfreq|  ",
      "After the conjugation and variant codes comes TENSE, VOICE, and MOOD.|         ",
      "     The TENSE, VOICE, AND MOOD codes are self descriptive.|                   ",
      "     Next comes PERSON (1, 2, 3: first, second, third person).|                ",
      "     Then the number (S, P: singular, plural).|                                ",
      Skip_Next, Bold_Next,
      "NOUN RESULTS. E.g.,|                                                           ",
      Bold_Next,
      "amor.is              N      3 1 GEN S M                   Always    mostfreq|  ",
      "3 1 are the declension and variant (see caveat re variants, above).|           ",
      "GEN is the CASE.  The abbreviations are self-descriptive.|                     ",
      "S is the NUMBER (S, P: singular, plural).|                                     ",
      "M is the GENDER (M, F, N, C: masc., fem. neuter, common masc./fem. form)|      ",
      Skip_Next, Bold_Next,
      "ADJECTIVE AND ADVERB RESULTS.  E.g.,|                                          ",
      Bold_Next,
      "amat.us              ADJ    1 1 NOM S M POS               Always    mostfreq|  ",
      "Adjectives and adverbs often include a COMPARISON-TYPE code (POS, COMP, SUPER).");

   CODES_HELP : constant Main_Help_Type :=
     (Underline_Next,
      "DICTIONARY CODES|                                                              ",
      Skip_Next, Bold_Next,
      "Example:|                                                                      ",
      Bold_Next,
      "[CDXAO]  =>       C     D              X           A             O|            ",
      Bold_Next,
      "The sequence is:  [age] [subject-area] [geography] [word freq.]  [source]|     ",
      Skip_Next,
      "Ages run from A to H, descending from A (archaic) to H (modern).|              ",
      "    TYPE ? AGE for more information.|                                          ",
      Skip_Next,
      "Subject-matter areas include E (eccl.), L (law, govt), B (bio.), W (war/mil.)| ",
      "    TYPE ? AREA for a complete list.|                                          ",
      Skip_Next,
      "There are 18 geographies.|                                                     ",
      "    TYPE ? GEO for a complete list.|                                           ",
      Skip_Next,
      "Word frequency codes run A to F, descending A (Always) to F (very rare).|      ",
      "    There are also four codes for special cases.|                              ",
      "    TYPE ? FREQ for more information.|                                         ",
      Skip_Next,
      "There are 28 source codes.|                                                    ",
      "    TYPE ? SOURCE for a complete list.|                                        ",
      Skip_Next,
      "  ***No scholarly rigor is assured.  This dictionary is an amateur project***| ");

   AGE_HELP : constant Main_Help_Type :=
     (Underline_Next,
      "AGE CODES|                                                                     ",
      Skip_Next, Bold_Next,
      "Age codes appear in the first dictionary-code position ('[AXXXX]')|            ",
      Bold_Next,
      "                                                          ^|                   ",
      Underline_Next,
      "code short name    meaning|                                                    ",
      "X    [null]        In use throughout the ages, unspecified, or unknown|        ",
      "A    archaic       Very early forms, obsolete by classical times|              ",
      "B    early         Early Latin, preclassical, or used for effect/poetry|       ",
      "C    classical     Limited to classical (~150 BC-200 AD)|                      ",
      "D    late          Late, post classical (3rd 5th centuries)|                   ",
      "E    later         Latin not in use in Classical times (6 10), Christian|      ",
      "F    medieval      Medieval (11th 15th centuries)|                             ",
      "G    scholar       16-18th century scholarly/scientific|                       ",
      "H    modern        Coined recently, words for new things (19-20th century)|    ",
      Skip_Next,
      "  ***No scholarly rigor is assured.  This dictionary is an amateur project***  ");

   AREA_HELP : constant Main_Help_Type :=
     (Underline_Next,
      "AREA CODES|                                                                    ",
      Skip_Next, Bold_Next,
      "Area codes appear in the second dictionary-code position ('[XAXXX]').|         ",
      Bold_Next,
      "                                                             ^|                ",
      Underline_Next,
      "code meaning|                                                                  ",
      "X    All, none, or not specified|                                              ",
      "A    Agriculture, flora, fauna, land, equipment, rural|                        ",
      "B    Biology, medical, body parts|                                             ",
      "D    Drama, music, theatre, art, painting sculpture|                           ",
      "E    Ecclesiastical, Biblical, religious|                                      ",
      "G    Grammar, rhetoric, logic, literature, school and education|               ",
      "L    Legal, government, tax, finance, politics, titles|                        ",
      "P    Poetic|                                                                   ",
      "S    Science, philosophy, mathematics, units and measures|                     ",
      "T    Technical, architecture, topography, surveying|                           ",
      "W    War, military, naval, ships, armor|                                       ",
      "Y    Mythology|                                                                ");

   GEO_HELP : constant Main_Help_Type :=
     (Underline_Next,
      "GEOGRAPHIC CODES|                                                              ",
      Skip_Next, Bold_Next,
      "Geographic codes appear in the third dictionary-code position ('[XXAXX]').|    ",
      Bold_Next,
      "                                                                   ^|          ",
      Underline_Next,
      "code meaning|                                                                  ",
      "X    All or none|                                                              ",
      "A    Africa|                                                                   ",
      "B    Britain|                                                                  ",
      "C    China|                                                                    ",
      "D    Scandinavia|                                                              ",
      "E    Egypt|                                                                    ",
      "F    France, Gaul|                                                             ",
      "G    Germany|                                                                  ",
      "H    Greece|                                                                   ",
      "I    Italy Rome|                                                               ",
      "J    India|                                                                    ",
      "K    Balkans|                                                                  ",
      "N    Netherlands|                                                              ",
      "P    Persia|                                                                   ",
      "Q    Near East|                                                                ",
      "R    Russia|                                                                   ",
      "S    Spain, Iberia|                                                            ",
      "U    Eastern Europe|                                                           ",
      Skip_Next,
      "The geographic codes are non-scientific approximations.|                       ");

   FREQ_HELP : constant Main_Help_Type :=
     (Underline_Next,
      "FREQUENCY CODES|                                                               ",
      Skip_Next,
      "There are two types of frequency codes:  The WORD frequency and|               ",
      "the INFLECTION (case or declension) frequency.|                                ",
      Skip_Next, Bold_Next,
      "Word frequency codes appear in the fourth dictionary-code position ('[XXXAX]').",
      Bold_Next,
      "                                                                         ^|    ",
      Underline_Next,
      "code short name   meaning|                                                     ",
      "X    unknown      unknown or unspecified|                                      ",
      "A    very freq    very frequent; common in basic textbooks|                    ",
      "B    frequent     top 10 percent (guestimate)|                                 ",
      "C    common       top 50 percent (guestimate)|                                 ",
      "D    lesser       bottom 40 percent (guestimate)|                              ",
      "E    uncommon     2 or 3 citations found|                                      ",
      "F    very rare    having only single citation in OLD or L+S|                   ",
      "I    inscription  only citation is inscription|                                ",
      "M    graffiti     graffiti form|                                               ",
      "N    Pliny        appears (almost) only in Pliny's Natural History|            ",
      Skip_Next, Bold_Next,
      "Inflection frequencies appear in the last column of inflection results.|       ",
      Skip_Next,
      "The inflection frequencies are output as descriptive short names:|             ",
      Underline_Next,
      "short name   meaning|                                                          ",
      "Unknown      unknown or unspecified|                                           ",
      "Most freq    very frequent, the most common|                                   ",
      "Sometimes    sometimes, a not unusual variant|                                 ",
      "Uncommon     occasionally seen|                                                ",
      "Infrequent   recognizable variant, but unlikely|                               ",
      "Rare         a few citations, very unlikely|                                   ",
      "Very rare    singular examples|                                                ",
      "Inscription  only citation is inscription|                                     ",
      Skip_Next,
      "  ***No scholarly rigor is assured.  This dictionary is an amatuer project***| ");

   SOURCE_HELP : constant Main_Help_Type :=
     (Underline_Next,
      "SOURCE CODES|                                                                  ",

      Skip_Next,
      "CAVEAT:  The sources refer to an authority against which the word was|         ",
      "         checked.  They are not precise.  Often several sources have been|     ",
      "         consulted.  Further, there are many un-named sources. With the|       ",
      "         of simple entries in old, out-of-copyright sources, the source|       ",
      "         materials are never copied and definitions not taken verbatim.|       ",
      "         However, the 'source' code is useful as a general guide to the|       ",
      "         degree of confidence.|                                                ",
      Skip_Next, Bold_Next,
      " Source codes appear in the last dictionary-code position ('[XXXXA]').|        ",
      Bold_Next,
      "                                                                 ^|            ",
      Underline_Next,
      "code    meaning|                                                               ",
      "A       [undefined]|                                                           ",
      "B       Beeson, C.H, A Primer of Medieval Latin, 1925 (Bee)|                   ",
      "C       Charles Beard, Cassell's Latin Dictionary 1892 (Cas)|                  ",
      "          OR Simpson, D.P., Cassells Latin & English Dictionary, 1987, which is",
      "          a reprint of Cassells New Compact, 1963) (NC Cas))|                  ",
      "D       Adams, J.N., Latin Sexual Vocabulary, 1982 (Sex)|                      ",
      "E       Stelten, L.F., Dictionary of Eccles. Latin, 1995 (Ecc)|                ",
      "F       Roy J. Deferrari, Dictionary of St. Thomas Aquinas, 1960 (DeF)|        ",
      "G       Gildersleeve + Lodge, Latin Grammar 1895 (G+L)|                        ",
      "H       Collatinus Dictionary by Yves Ouvrard|                                 ",
      "I       Leverett, F.P., Lexicon of the Latin Language, Boston 1845|            ",
      "J       Bracton, De Legibus Et Consuetudinibus Angli|                          ",
      "K       Calepinus Novus, modern Latin, by Guy Licoppe (Cal)|                   ",
      "L       Lewis, C.S., Elementary Latin Dictionary 1891|                         ",
      "M       Latham, Revised Medieval Word List, 1980 (Latham)|                     ",
      "N       Lynn Nelson, Wordlist (Nel)|                                           ",
      "O       Oxford Latin Dictionary (OLD), 1982 (mostly), 2012 (on occasion)|      ",
      "P       Souter, A Glossary of Later Latin to 600 A.D., Oxford 1949 (Souter)|   ",
      "Q       Other, cited or unspecified dictionaries|                              ",
      "R       Plater + White, A Grammar of the Vulgate, Oxford 1926 (Plater)|        ",
      "S       Lewis and Short, A Latin Dictionary, 1879 (L+S)|                       ",
      "T       Found in a translation  no dictionary reference|                       ",
      "U       [undefined]|                                                           ",
      "V       Vademecum in opus Saxonis|                                             ",
      "W       Gen. Whitaker's personal guess, mostly obvious extrapolation|          ",
      "Y       Gen. Whitaker's undefined 'temporary' special code|                    ",
      "Z       Sent by user--no dictionary reference|                                 ",
      Skip_Next,
      "Where sources provide uncertain, conflicting, or substantially unique means|   ",
      "is indicated in the meaning line with the abbreviations in parentheses above.| ",
      "for example 'xxx (OLD); yyy (L+S)' means that gist of the OLD's definition|    ",
      "'xxx' but Lewis and Short says 'yyy'.|                                         ",
      Skip_Next,
      "TYPE ? MEANINGS to learn more about other abbreviations and codes used in|     ",
      "meanings (definition) lines.|                                                  ");

   PEARSE_HELP : constant Main_Help_Type :=
     (Underline_Next,
      "PEARSE CODES|                                                                  ",
      Skip_Next,
      "Pearse codes are numerical codes 01 through 06 that indicate the type of|      ",
      "information on a line. They're useful when processing the program's output.|   ",
      Skip_Next, Underline_Next,
      "01   forms|                                                                    ",
      "02   dictionary forms (incl. Area, geography, age, source codes)|              ",
      "03   definition|                                                               ",
      "04   unknown word|                                                             ",
      "05   contains addon|                                                           ",
      "06   warnings, notes (esp. tricks)|                                            ",
      "07   notice that data written to file (other than WORD.OUT or WORD.UNK|        ");

   MEANING_HELP : constant Main_Help_Type :=
     (Underline_Next,
      "ABBREVIATIONS IN MEANING LINES|                                                ",
      Skip_Next, Bold_Next,
      ":     used with an AREA code to specify a single special meaning appropriate.| ",
      Skip_Next, Bold_Next,
      "?     implies some doubt about the word's existence or interpretation.|        ",
      Skip_Next, Bold_Next,
      "~     stands for the stem or word in question.|                                ",
      Skip_Next, Bold_Next,
      "=>    indicates a frequent idiom, usage, or a translation example|             ",
      Skip_Next, Bold_Next,
      "abb.  abbreviation|                                                            ",
      Bold_Next, Skip_Next,
      "(Dif) Diferrari|                                                               ",
      "      is used to indicate an additional meaning taken from A Latin-English|    ",
      "      Dictionary of St. Thomas Aquinas by Roy J. Diferrari. This is singled|   ",
      "      out because of the importance of Aquinas. The reference applies from|    ",
      "      the last semicolon before the mark. It is likely that the meaning|       ",
      "      diverges from the base by being medieval and ecclesiastical, but|        ",
      "      not so overwhelming as to deserve a separate entry.|                     ",
      Skip_Next, Bold_Next,
      "(Douay)|                                                                       ",
      "      is used to designate those words for which the meaning has been derived| ",
      "      or modified by examination of the Douay translation of the Latin|        ",
      "      Vulgate Bible of St Jerome.|                                             ",
      Skip_Next, Bold_Next,
      "(Ecc.)|                                                                        ",
      "      designating a special church meaning in a list of conventional meanings,|",
      "      an additional meaning not sufficient to justify a separate entry with|   ",
      "      an ecclesiastical code.|                                                 ",
      Skip_Next, Bold_Next,
      "(KJames)|                                                                      ",
      "      is used to designate those words for which the meaning has been derived| ",
      "      or modified by examination of the King James Bible in connection with the",
      "      Latin Vulgate Bible of St Jerome|                                        ",
      Skip_Next, Bold_Next,
      "(KLUDGE)|                                                                      ",
      "      This indicates that the particular form is distorted in order to make|   ",
      "      it come out correctly. This usually takes the form of a special|         ",
      "      conjugational form applied to a few words, not applicable to other|      ",
      "      words of the same conjugation or declension. The user can expect the|    ",
      "      form and meaning to be correct, but the numerical coding will be odd.|   ",
      Skip_Next, Bold_Next,
      "(L+S) Lewis & Short|                                                           ",
      "      indicates either: (i) the meaning in L+S meaning departs significantly|  ",
      "      from the Oxford Latin Dictionary (OLD); or (ii) the spelling differs|    ",
      "      slightly between the two dictionaries. In situation (ii), there will|    ",
      "      entries for both spellings.  The dictionary code (type ? CODES for|      ",
      "      information) will identify from which dictionary the entry's spelling|   ",
      "      comes.|                                                                  ",
      Skip_Next, Bold_Next,
      "NT    New Testament|                                                           ",
      Skip_Next, Bold_Next,
      "(OLD) Oxford Latin Dictionary|                                                 ",
      "      identifies supplemental information from the OLD for entries that the|   ",
      "      dictionary code (type ? CODES for information) indicates were primarily| ",
      "      checked against a different dictionary.|                                 ",
      Skip_Next, Bold_Next,
      "OT    Old Testament|                                                           ",
      Skip_Next, Bold_Next,
      "(PASS)                                                                         ",
      "      indicates a special, unexpected meaning for the passive form that is|    ",
      "      not easily associated with the active meaning. (PASS) is also often|     ",
      "      used to remind the user that compounds of facio form the passive|        ",
      "      by using the active of fio. E.g., calefio (calefacio PASS). There may|   ",
      "      be more translation information in the entry for the cited base word.|   ",
      Skip_Next, Bold_Next,
      "perh. perhaps|                                                                 ",
      "      denotes an uncertainty, but not as strong as (?).|                       ",
      Skip_Next, Bold_Next,
      "(pl.) plural|                                                                  ",
      "      means that the Latin word is believed by scholars to be used (almost)|   ",
      "      always in the plural form when used with the meaning stated, even if the|",
      "      English meaning is singular. If it appears in the beginning of the|      ",
      "      meaning, before the first comma, it applies to all the meanings. If it|  ",
      "      appears later, it applies only to that and later meanings. The program|  ",
      "      does not necessarily exclude a singular form in the output. While it may|",
      "      be true that in good, classical Latin it is never used in the singular,| ",
      "      it may in some texts appear in the singular. The TRIM_OUTPUT option may| ",
      "      cause only plural forms to appear, with no TRIM_OUTPUT the singular will|",
      "      be shown.                                                                ",
      Skip_Next, Bold_Next,
      "prob. probably|                                                                ",
      "      denotes some uncertainty, but not as much as (perh.).|                   ",
      Skip_Next, Bold_Next,
      "pure Latin|                                                                    ",
      "      indicates a pure Latin term for a word which is derived from another|    ",
      "      language (almost certainly Greek).|                                      ",
      Skip_Next, Bold_Next,
      "(rude)|                                                                        ",
      "      indicates that this meaning was used in a rude, vulgar, coarse, or|      ",
      "      obscene manner, not what one should hear in polite company. Such use is| ",
      "      likely from graffiti or epigrams, or in plays in which the dialogue is|  ",
      "      to indicate that the characters are low or crude. Meanings given by|     ",
      "      the program for these words are more polite, and the user is invited to| ",
      "      substitute the current street language or obscenity of his choice to|    ",
      "      get the flavor of text.|                                                 ",
      Skip_Next, Bold_Next,
      "(sg.)|                                                                         ",
      "      means that the Latin word is believed to be used always in the singular.|",
      "      It applies to the meaning behind which it appears, as well as to any|    ",
      "      subsequent meanings that follow a comma but before a semicolon.|         ",
      Skip_Next, Bold_Next,
      "  ***No scholarly rigor is assured.  This dictionary is an amateur project***| ");

   Param_Help : constant Main_Help_Type :=
     ("Words operates in two modes when using command-line arguments|                 ",
      Bold_Next,
      "[1] NON-INTERACTIVE WORDS:  Fully compatible with Wm. Whitaker's classic Words.",
      "Usage:|                                                                        ",
      "words [string of Latin words]|                                                 ",
      "   => send results for the Latin words to standard output and exit|            ",
      "words [in_file] [out_file]|                                                    ",
      "   => take Latin words from the in_file and put the results in out_file|       ",
      "words " & CHANGE_LANGUAGE_CHARACTER &
      "e [(POS) English word(s)string]|                                        ",
      "   => returns Latin translation options|                                       ",
      "   POS uses abbreviations in ? GRAMMAR; applies only to first English word|    ",
      Skip_Next, Bold_Next,
      "[2] MODIFIED INTERACTIVE-MODE:  Set limits on interactive mode.|               ",
      "Options:|                                                                      ",
      "-r    NO CHANGE:     User cannot CHANGE settings or update local dictionary|   ",
      "-n    NO FILES:      User cannot SAVE settings, update local dictionary, use|  ",
      "                     file input, or CHANGE user log settings (WRITE_...TO_FILE)",
      "-x    NO EXIT:       User cannot exit with two returns or control-C|           ",
      "           NOT A SECURE MODE - only blocks SIGINT|                             ",
      "           No effect on suspend (SIGSTP) or kill (SIGTERM)|                    ",
      "-l    LATIN ONLY:    User cannot enter English->Latin mode|                    ",
      "-e    ENGLISH ONLY:  User cannot enter Latin->English mode|                    ",
      "-m    MEANINGS ONLY: Limit Latin->English output to dictionary line and meaning",
      "E.g., words -rnlm limits the user the functionality of a paper dictionary|     ",
      "Command-line options override any conflicting settings in WORD.MOD|            ");

end Words_Help;
